# can switch back and forth between the project types exported by the extensions for testing

project:
  #   type: qtest
  type: qtest2

website:
  navbar:
    left:
      - href: apage.qmd
        text: A Page
